dist: bionic
language: minimal
env:
  global:
    - BASE_IMAGE=fedora:31
    - TEST_CMD="./script/test.sh"

.com.github.junaruga.ruby-jit-test.definitions:
  - &container-run
    script:
      - |
        docker run --rm -t test/ruby-jit ${TEST_CMD}

  - &test_in_container
    install:
      - |
        travis_retry docker build --rm -t test/ruby-jit \
          -f ci/Dockerfile-fedora \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          .
    <<: *container-run

  - &test_module_in_container
    install:
      - |
        travis_retry docker build --rm -t test/ruby-jit \
          -f ci/Dockerfile-rhel \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          --build-arg RUBY_MODULE_STREAM=${RUBY_MODULE_STREAM} \
          .
    <<: *container-run

  - &test_scl_in_container
    install:
      - |
        travis_retry docker build --rm -t test/ruby-jit \
          -f ci/Dockerfile-rhel-scl \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          --build-arg RUBY_SCL=${RUBY_SCL} \
          .
    <<: *container-run

jobs:
  include:
    - name: "Fedora rawhide Ruby 2.7"
      env:
        - BASE_IMAGE=fedora:rawhide
      <<: *test_in_container
    - name: "Fedora 31 Ruby 2.6"
      env:
        - BASE_IMAGE=fedora:31
      <<: *test_in_container
    - name: "Fedora 30 Ruby 2.6"
      env:
        - BASE_IMAGE=fedora:30
      <<: *test_in_container
    - name: "RHEL 8.1 Module Ruby 2.6"
      env:
        - BASE_IMAGE=registry.access.redhat.com/ubi8:8.1
        - RUBY_MODULE_STREAM=2.6
      <<: *test_module_in_container
    - name: "RHEL 7.7 SCL Ruby 2.6"
      env:
        - BASE_IMAGE=registry.access.redhat.com/ubi7:7.7
        - RUBY_SCL=rh-ruby26
        - TEST_CMD="scl enable $RUBY_SCL ./script/test.sh"
      <<: *test_scl_in_container
  allow_failures:
    - name: "RHEL 8.1 Module Ruby 2.6"
  fast_finish: true
branches:
  except:
    - /^wip\//
